### ISSUE TITLE
graphql not working as expected

### ISSUE THREAD

**Issue by WaseemRakab** [adelsz/graphql-deno#1]
with deno version 1.0.1, graphql no longer works.
this errors occurred
`
error: TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/adelsz/graphql-deno/v15.0.0/mod"' has no exported member 'graphql'.
    graphql,
    ~~~~~~~
    at file:///C:/Users/sc12/Downloads/AngularProjects/Deno/deps/deps.ts:7:5

TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/adelsz/graphql-deno/v15.0.0/mod"' has no exported member 'GraphQLSchema'.
    GraphQLSchema,
    ~~~~~~~~~~~~~
    at file:///C:/Users/***/Deno/deps/deps.ts:8:5

TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/adelsz/graphql-deno/v15.0.0/mod"' has no exported member 'GraphQLObjectType'.
    GraphQLObjectType,
    ~~~~~~~~~~~~~~~~~
    at file:///C:/Users/***/Deno/deps/deps.ts:9:5

TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/adelsz/graphql-deno/v15.0.0/mod"' has no exported member 'GraphQLString'.
    GraphQLString,
    ~~~~~~~~~~~~~
    at file:///C:/Users/***/Deno/deps/deps.ts:10:5

Found 4 errors.
`

**Comment by adelsz** [comment]
Thanks for reporting!
This does look like a deno bug. I have added a workaround for it, so it should work now.
Make sure to clean your Deno cache directory before retrying. To find the cache dir: `deno info | grep 'Remote modules cache:'`
